# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='page_url',
            field=models.URLField(max_length=255),
        ),
    ]
