# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='species', to='contenttypes.ContentType'),
        ),
    ]
