# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20180112_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_url',
            field=models.URLField(max_length=255, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='page_url',
            field=models.URLField(max_length=255, verbose_name='Page URL'),
        ),
    ]
