# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
    ]
