# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0002_auto_20180129_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampling',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
