# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_sampling_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
