# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0004_auto_20190730_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ecotype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
