# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 13:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=10, unique=True)),
                ('animal_sex', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_litter_size', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tail_type', models.CharField(blank=True, choices=[('FT', 'fat-tailed'), ('TT', 'thin-tailed'), ('FR', 'fat-rumped')], max_length=2)),
                ('tail_shape', models.CharField(blank=True, choices=[('L', 'long'), ('S', 'short')], max_length=1)),
                ('further_tail_description', models.CharField(blank=True, max_length=200)),
                ('possible_related_breed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('site', models.CharField(blank=True, choices=[('C', 'communal grazing field'), ('V', 'village')], max_length=100)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('altitude', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('locality', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep_samplings', to='contenttypes.ContentType')),
                ('population', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sampling', to='sheep.Population')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='sampling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='sheep.Sampling'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to='animals.Species'),
        ),
    ]
