# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
        ('sheep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampling',
            name='contact_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sheep_samplings', to='studies.Study'),
            preserve_default=False,
        ),
    ]
