# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-29 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='accession_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sample_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
