# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheep', '0002_sampling_contact_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampling',
            old_name='contact_person',
            new_name='study',
        ),
    ]
