# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=20)),
                ('tag', models.CharField(blank=True, max_length=30, verbose_name='tag number or color')),
                ('animal_sex', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('origin', models.CharField(blank=True, choices=[('FG', 'Farmgate'), ('MA', 'Market'), ('NE', 'Neighbour'), ('ES', 'Extension service input delivery'), ('NG', 'NGO')], max_length=2)),
                ('phenotypical_characteristics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('vaccination', models.CharField(blank=True, max_length=100)),
                ('treatment', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('village', models.CharField(blank=True, max_length=50)),
                ('soil_type', models.CharField(blank=True, choices=[('VS', 'Vertisol'), ('SC', 'Sandy and clay'), ('SA', 'Sandy')], max_length=2)),
                ('vegetation_type', models.CharField(blank=True, choices=[('FO', 'Forest'), ('SH', 'Shrub'), ('RL', 'Range land/grass'), ('BL', 'Bare land')], max_length=2)),
                ('agroecology', models.CharField(blank=True, max_length=100)),
                ('rainfall_pattern', models.CharField(blank=True, choices=[('U', 'Unimodal'), ('B', 'Bimodal')], max_length=1)),
                ('water_source', models.CharField(blank=True, choices=[('WE', 'Well'), ('TW', 'Tap water'), ('RI', 'River'), ('SW', 'Spring water'), ('DW', 'Deep well pump water')], max_length=2)),
                ('coop_type', models.CharField(blank=True, max_length=100)),
                ('previous_illnes_occurence', models.CharField(blank=True, max_length=100)),
                ('chicken_feed', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('other_animals', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Relatedness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('PA', 'parent'), ('SI', 'sibling'), ('HS', 'half-sibling'), ('MH', 'maternal half-sibling'), ('PH', 'paternal half-sibling')], max_length=2)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='chickens.Animal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='chickens.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('colon_length', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='colon length (cm)')),
                ('caecum_length', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='caecum length (cm)')),
                ('fat_status', models.CharField(blank=True, choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=1, verbose_name='Status of fat on the colon and caecum')),
                ('caecal_parasites', models.CharField(blank=True, max_length=100)),
                ('other_observations', models.CharField(blank=True, max_length=100)),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='estimated age (months)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='weight (kg)')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sampling', to='chickens.Animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='chickens.Farm'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedness',
            unique_together=set([('source', 'target')]),
        ),
    ]
