# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='animals.Species'),
            preserve_default=False,
        ),
    ]
