# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0002_animal_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chickens', to='animals.Species'),
        ),
    ]
