# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 09:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_auto_20180109_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='chicken_feed',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='other_animals',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
