country_mapping = {
    'id' : 'ID_0',
    'iso' : 'ISO',
    'name_english' : 'NAME_ENGLI',
    'name_iso' : 'NAME_ISO',
    'name_fao' : 'NAME_FAO',
    'name_local' : 'NAME_LOCAL',
    'name_obsolete' : 'NAME_OBSOL',
    'name_variants' : 'NAME_VARIA',
    'name_nonlatin' : 'NAME_NONLA',
    'name_french' : 'NAME_FRENC',
    'name_spanish' : 'NAME_SPANI',
    'name_russian' : 'NAME_RUSSI',
    'name_arabic' : 'NAME_ARABI',
    'name_chinese' : 'NAME_CHINE',
    'waspartof' : 'WASPARTOF',
    'contains' : 'CONTAINS',
    'sovereign' : 'SOVEREIGN',
    'iso2' : 'ISO2',
    'www' : 'WWW',
    'fips' : 'FIPS',
    'ison' : 'ISON',
    'validfr' : 'VALIDFR',
    'validto' : 'VALIDTO',
    'pop2000' : 'POP2000',
    'sqkm' : 'SQKM',
    'popsqkm' : 'POPSQKM',
    'unregion1' : 'UNREGION1',
    'unregion2' : 'UNREGION2',
    'developing' : 'DEVELOPING',
    'cis' : 'CIS',
    'transition' : 'Transition',
    'oecd' : 'OECD',
    'wbregion' : 'WBREGION',
    'wbincome' : 'WBINCOME',
    'wbdebt' : 'WBDEBT',
    'wbother' : 'WBOTHER',
    'ceeac' : 'CEEAC',
    'cemac' : 'CEMAC',
    'ceplg' : 'CEPLG',
    'comesa' : 'COMESA',
    'eac' : 'EAC',
    'ecowas' : 'ECOWAS',
    'igad' : 'IGAD',
    'ioc' : 'IOC',
    'mru' : 'MRU',
    'sacu' : 'SACU',
    'uemoa' : 'UEMOA',
    'uma' : 'UMA',
    'palop' : 'PALOP',
    'parta' : 'PARTA',
    'cacm' : 'CACM',
    'eurasec' : 'EurAsEC',
    'agadir' : 'Agadir',
    'saarc' : 'SAARC',
    'asean' : 'ASEAN',
    'nafta' : 'NAFTA',
    'gcc' : 'GCC',
    'csn' : 'CSN',
    'caricom' : 'CARICOM',
    'eu' : 'EU',
    'can' : 'CAN',
    'acp' : 'ACP',
    'landlocked' : 'Landlocked',
    'aosis' : 'AOSIS',
    'sids' : 'SIDS',
    'islands' : 'Islands',
    'ldc' : 'LDC',
    'geom' : 'MULTIPOLYGON',
}


adm1_mapping = {
    'country' : {'id': 'ID_0'},
    'id_0' : 'ID_0',
    'iso' : 'ISO',
    'name_0' : 'NAME_0',
    'id_1' : 'ID_1',
    'name_1' : 'NAME_1',
    'hasc_1' : 'HASC_1',
    'ccn_1' : 'CCN_1',
    'cca_1' : 'CCA_1',
    'type_1' : 'TYPE_1',
    'engtype_1' : 'ENGTYPE_1',
    'nl_name_1' : 'NL_NAME_1',
    'varname_1' : 'VARNAME_1',
    'geom' : 'MULTIPOLYGON',
}


adm2_mapping = {
    'country' : {'id': 'ID_0'},
    'id_0' : 'ID_0',
    'iso' : 'ISO',
    'name_0' : 'NAME_0',
    'id_1' : 'ID_1',
    'name_1' : 'NAME_1',
    'id_2' : 'ID_2',
    'name_2' : 'NAME_2',
    'hasc_2' : 'HASC_2',
    'ccn_2' : 'CCN_2',
    'cca_2' : 'CCA_2',
    'type_2' : 'TYPE_2',
    'engtype_2' : 'ENGTYPE_2',
    'nl_name_2' : 'NL_NAME_2',
    'varname_2' : 'VARNAME_2',
    'geom' : 'MULTIPOLYGON',
}


adm3_mapping = {
    'country' : {'id': 'ID_0'},
    'id_0' : 'ID_0',
    'iso' : 'ISO',
    'name_0' : 'NAME_0',
    'id_1' : 'ID_1',
    'name_1' : 'NAME_1',
    'id_2' : 'ID_2',
    'name_2' : 'NAME_2',
    'id_3' : 'ID_3',
    'name_3' : 'NAME_3',
    'ccn_3' : 'CCN_3',
    'cca_3' : 'CCA_3',
    'type_3' : 'TYPE_3',
    'engtype_3' : 'ENGTYPE_3',
    'nl_name_3' : 'NL_NAME_3',
    'varname_3' : 'VARNAME_3',
    'geom' : 'MULTIPOLYGON',
}


adm4_mapping = {
    'country' : {'id': 'ID_0'},
    'id_0' : 'ID_0',
    'iso' : 'ISO',
    'name_0' : 'NAME_0',
    'id_1' : 'ID_1',
    'name_1' : 'NAME_1',
    'id_2' : 'ID_2',
    'name_2' : 'NAME_2',
    'id_3' : 'ID_3',
    'name_3' : 'NAME_3',
    'id_4' : 'ID_4',
    'name_4' : 'NAME_4',
    'varname_4' : 'VARNAME_4',
    'ccn_4' : 'CCN_4',
    'cca_4' : 'CCA_4',
    'type_4' : 'TYPE_4',
    'engtype_4' : 'ENGTYPE_4',
    'geom' : 'MULTIPOLYGON',
}


adm5_mapping = {
    'country' : {'id': 'ID_0'},
    'id_0' : 'ID_0',
    'iso' : 'ISO',
    'name_0' : 'NAME_0',
    'id_1' : 'ID_1',
    'name_1' : 'NAME_1',
    'id_2' : 'ID_2',
    'name_2' : 'NAME_2',
    'id_3' : 'ID_3',
    'name_3' : 'NAME_3',
    'id_4' : 'ID_4',
    'name_4' : 'NAME_4',
    'id_5' : 'ID_5',
    'name_5' : 'NAME_5',
    'ccn_5' : 'CCN_5',
    'cca_5' : 'CCA_5',
    'type_5' : 'TYPE_5',
    'engtype_5' : 'ENGTYPE_5',
    'geom' : 'MULTIPOLYGON',
}
