# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name_english',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fifthadministrativelevel',
            options={'ordering': ('id_0', 'id_1', 'id_2', 'id_3', 'id_4', 'id_5'), 'verbose_name': '5th level administrative area', 'verbose_name_plural': '5h level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='firstadministrativelevel',
            options={'ordering': ('id_1',), 'verbose_name': '1st level administrative area', 'verbose_name_plural': '1st level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='fourthadministrativelevel',
            options={'ordering': ('id_0', 'id_1', 'id_2', 'id_3', 'id_4'), 'verbose_name': '4th level administrative area', 'verbose_name_plural': '4th level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='secondadministrativelevel',
            options={'ordering': ('id_0', 'id_1', 'id_2'), 'verbose_name': '2nd level administrative area', 'verbose_name_plural': '2nd level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='thirdadministrativelevel',
            options={'ordering': ('id_0', 'id_1', 'id_2', 'id_3'), 'verbose_name': '3rd level administrative area', 'verbose_name_plural': '3rd level administrative areas'},
        ),
    ]
