# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0002_auto_20180129_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fifthadministrativelevel',
            options={'ordering': ('name_0', 'name_1', 'name_2', 'name_3', 'name_4', 'name_5'), 'verbose_name': '5th level administrative area', 'verbose_name_plural': '5h level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='firstadministrativelevel',
            options={'ordering': ('name_0', 'name_1'), 'verbose_name': '1st level administrative area', 'verbose_name_plural': '1st level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='fourthadministrativelevel',
            options={'ordering': ('name_0', 'name_1', 'name_2', 'name_3', 'name_4'), 'verbose_name': '4th level administrative area', 'verbose_name_plural': '4th level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='secondadministrativelevel',
            options={'ordering': ('name_0', 'name_1', 'name_2'), 'verbose_name': '2nd level administrative area', 'verbose_name_plural': '2nd level administrative areas'},
        ),
        migrations.AlterModelOptions(
            name='thirdadministrativelevel',
            options={'ordering': ('name_0', 'name_1', 'name_2', 'name_3'), 'verbose_name': '3rd level administrative area', 'verbose_name_plural': '3rd level administrative areas'},
        ),
    ]
