# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0003_auto_20180130_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='contains',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_nonlatin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_obsolete',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_variants',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='country',
            name='waspartof',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='wbother',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='country',
            name='www',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
